spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imagebackup?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123~qwer
    
dev:
  redis:
    url: 127.0.0.1
    port: 6379
  panoramaAPI:
    panoramaImageIDAPI: http://test-admin.panorama.map.naver.com/admin/captcha/
    panoramaImageAPI: https://test-panorama.map.naver.com/api/v2/thumbnail/
    
    
